name: Build Windows GUI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_Version3.txt
        python -m pip install pyinstaller
        
    - name: Build GUI executable
      run: |
        # Create modpack_doctor.py symlink if it doesn't exist (for compatibility)
        if (!(Test-Path "modpack_doctor.py")) {
          New-Item -ItemType SymbolicLink -Path "modpack_doctor.py" -Target "modpack_doctor_Version3.py"
        }
        
        pyinstaller --noconsole --onefile modpack_doctor_gui.py `
          --name ModpackDoctor-GUI `
          --add-data "modpack_doctor_Version3.py;." `
          --add-data "modpack_doctor.py;." `
          --add-data "data_known_conflicts_Version3.json;." `
          --add-data "data_performance_mods_Version3.json;."
      shell: powershell
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ModpackDoctor-GUI-windows
        path: dist/ModpackDoctor-GUI.exe
        if-no-files-found: error
        compression-level: 9
        retention-days: 14